name: Update Dashboard Data

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests yfinance

      - name: Fetch stock data
        run: |
          python << 'EOF'
          import json
          import yfinance as yf
          from datetime import datetime

          # Stock tickers to track
          tickers = ['LLY', 'NVO', 'VKTX', 'AMGN', 'RHHBY', 'PFE']
          
          stocks_data = []
          
          for ticker_symbol in tickers:
              try:
                  ticker = yf.Ticker(ticker_symbol)
                  info = ticker.info
                  hist = ticker.history(period='2d')
                  
                  if len(hist) >= 2:
                      current_price = hist['Close'].iloc[-1]
                      prev_close = hist['Close'].iloc[-2]
                      change = current_price - prev_close
                      change_percent = (change / prev_close) * 100
                  else:
                      current_price = info.get('currentPrice', 0)
                      prev_close = info.get('previousClose', current_price)
                      change = current_price - prev_close
                      change_percent = (change / prev_close) * 100 if prev_close else 0
                  
                  # Format market cap
                  market_cap = info.get('marketCap', 0)
                  if market_cap >= 1e12:
                      market_cap_str = f"{market_cap / 1e12:.1f}T"
                  elif market_cap >= 1e9:
                      market_cap_str = f"{market_cap / 1e9:.1f}B"
                  elif market_cap >= 1e6:
                      market_cap_str = f"{market_cap / 1e6:.1f}M"
                  else:
                      market_cap_str = str(market_cap)
                  
                  stock_data = {
                      'ticker': ticker_symbol,
                      'company': info.get('longName', ticker_symbol),
                      'price': round(current_price, 2),
                      'change': round(change, 2),
                      'changePercent': round(change_percent, 2),
                      'marketCap': market_cap_str
                  }
                  
                  stocks_data.append(stock_data)
                  print(f"✓ Fetched {ticker_symbol}: ${current_price:.2f}")
                  
              except Exception as e:
                  print(f"✗ Error fetching {ticker_symbol}: {e}")
                  continue
          
          # Create output JSON
          output_data = {
              'lastUpdated': datetime.utcnow().isoformat() + 'Z',
              'stocks': stocks_data
          }
          
          # Write to file
          with open('public/dashboard_data.json', 'w') as f:
              json.dump(output_data, f, indent=2)
          
          print(f"\n✓ Successfully updated dashboard_data.json with {len(stocks_data)} stocks")
          EOF

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/dashboard_data.json
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update stock data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "✓ Changes committed and pushed"
          fi
